apiVersion : apps/v1
kind: Deployment
metadata:
  name: femipringbootapp 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: femipringbootapp
  template:
    metadata:
      labels:
        app: femipringbootapp 
    spec:
      containers:
        - name: femibootapp 
          image: myacr131femi.azurecr.io/femipringbootapp
          ports:
          - containerPort: 80
